from transformers import pipeline

summarizer = pipeline("summarization", model="Falconsai/text_summarization")

ARTICLE = """
Les systèmes techniques informatiques (STI) 
Au milieu du XXe siècle, grâce aux progrès de la conduction analogique et numérique du courant électrique les systèmes techniques informatiques (STI) émergent. Ils rassemblent les éléments matériels, les langages de programmation, les flux de données et l’organisation (Reix et al., 2011). Ils sont les premiers automates à résoudre avec précision, comme les humains, les opérations pour lesquelles ils ont été conçus à (Walsh 2018). Bien que les systèmes techniques forment l'appareillage des civilisations humaines depuis la préhistoire, les STI demeurent l’aventure la plus fascinante de l’histoire (Marcinkowski et Wilgaux 2004). L’ENIAC effectuait les calculs de balistique des tables de tir que l’État-Major de l’armée américaine confiait à plus de deux cents personnes (Aubert, 1997). Volle (2006) souligne que les STI aident à l’optimisation des processus de production en stimulant l’intelligence humaine. Son évolution dans les organisations amène le numérique à occuper une place privilégiée en contribuant à un travail plus intelligente avec l’apport des informations (Boussay et al., 2015). Aberkane (2017) remarque que ce ne sont pas des outils techniques simplement mais une contribution significative au renouvellement de l’effort cérébral et de l’intelligence individuelle et collective.  Ils oscillent, dans la compétition des intelligences, entre le monde inanimé des objets et le monde animé des humain (Triclot 2004). Pour Michel Serres (1930-2019), les STI sont les seuls outils dont l’universalité ne permet plus de différencier les métiers. Comme le souligne Delavallée (2016), ils métamorphosent les structures, les processus organisationnels et les comportements individuels et collectifs au fur et à mesure qu’ils réinventent les métiers. Ses mécanismes de création, d’acquisition, de transfert et d’utilisation des données, des informations et des connaissances progressent en assurant la performance organisationnelle.  Aussi, parait-il important de considérer l’évolution des STI dans les organisations à la lumière des idées de Nurcan & Rolland (2006), de Figer (2008) et de Bidan (2017).

Ainsi, la succession des systèmes techniques mécaniques (STM), des systèmes techniques énergétiques (STE) et des systèmes techniques informatiques (STI) constitue les fondements de la GSTI dans les organisations.

"""
print(summarizer(ARTICLE, max_length=1000, min_length=30, do_sample=False))
>>> [{'summary_text': 'Hugging Face has emerged as a prominent and innovative force in NLP . From its inception to its role in democratizing AI, the company has left an indelible mark on the industry . The name "Hugging Face" was chosen to reflect the company\'s mission of making AI models more accessible and friendly to humans .'}]
